import Head from "next/head";
import { useQuery } from "react-query";
import { getPapers } from "./../lib/helpers";
import * as RiIcon from "react-icons/ri";
import Link from "next/link";
import PaperBox from "../components/PaperBox";

export default function Home() {
  const { data, isLoading, isError } = useQuery("papers", getPapers);

  if (isLoading) return <div>LOADING... </div>;

  return (
    <>
      <Head>
        <title>TodoApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="max-w-7xl mx-auto py-20 flex items-center justify-between flex-wrap flex-col md:flex-row gap-y-4">
        {data.length === 0 ? (
          <div>No Paper ...</div>
        ) : (
          data?.map((item) => <PaperBox key={item._id} item={item} />)
        )}
      </section>
      
    </>
  );
}
